### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by msaroufim** [pytorch/torchx#197]
## 📚 Documentation

At a high level the repo really needs a glossary of terms in a single page otherwise easy to forget what they mean when you get to a new page. Lots of content can be deleted specifically the example application notebooks don't add anything relative to the pipeline examples.

General list of feedback - not sure how to fix yet so opening issue instead of PR

### https://pytorch.org/torchx/latest/quickstart.html

* Add a link to where built in are defined in the code

### https://pytorch.org/torchx/latest/cli.html

* App bundle is never defined - is it the app ID? in the docs `echo_c944ffb2`?

### https://pytorch.org/torchx/latest/configure.html

* One thing wasn't too clear is a resource basically number of CPUs and GPUs? Would be helpful to add some helper enum which includes something higher level like a V100 machine for provisioning

### https://pytorch.org/torchx/latest/examples_apps/datapreproc/component.html#sphx-glr-examples-apps-datapreproc-component-py

* Example has no main function

### https://pytorch.org/torchx/latest/examples_apps/datapreproc/datapreproc.html#sphx-glr-examples-apps-datapreproc-datapreproc-py

I'm not sure what the entire Application Examples notebooks do? May be best to refactor together with pipeline examples? Let me know I can send a PR to delete

### https://pytorch.org/torchx/latest/examples_pipelines/kfp/intro_pipeline.html#sphx-glr-examples-pipelines-kfp-intro-pipeline-py

* Make it clearer that pipeline.yaml is generated and not an input - I kept looking for it in the source directory

### https://pytorch.org/torchx/latest/components/base.html

Why is torch.elastic mentioned here? Whole repo feels like it needs a glossary. For example by image do you mean docker image?

### https://pytorch.org/torchx/latest/components/hpo.html

* Just sat TBD - delete for now?

### https://pytorch.org/torchx/latest/components/utils.html

* Have a link to supported utils in the codebase

### https://pytorch.org/torchx/latest/schedulers/kubernetes.html

* This says coming soon but looks like feature is available?

### https://pytorch.org/torchx/latest/beta.html

Also empty just remove

**Comment by aivanou** [comment]
Hi @msaroufim  !
Thank you very much for doc feedback, we will make the relevant changes to our doc to make them better. 
Will be attaching PRs to this diff that change docs.
-Aliaksadr

**Comment by d4l3k** [comment]
@msaroufim one other thing is that the docs have changed quite a bit in main pending rc/stable release. The docs for "latest" correspond to released pip version. 

Feedback should be for the pre-release docs at https://pytorch.org/torchx/main/ since things have changed

**Comment by kiukchung** [comment]
Appreciate the feedback. Looks like most of the point of confusion has been addressed in our HEAD (main) docs: https://pytorch.org/torchx/main/. Please do keep in mind that TorchX is still in beta hence its worth checking out the "main" docs until we are fully in stable.

In addition to the comments above, here are a few others:

=====
> Lots of content can be deleted specifically the example application notebooks don't add anything relative to the pipeline examples.

could you elaborate? the apps examples don't really relate to pipelines and are intended to showcase: 1) authoring of executables in an "infra-agnostic" manner 2) demonstrating an app as a standalone job (not a pipeline stage)

=====
> repo really needs a glossary of terms in a single page

Have you seen https://pytorch.org/torchx/latest/basics.html#concepts? 

=====
> Add a link to where built in are defined in the code

see: https://pytorch.org/torchx/latest/basics.html#project-structure

=====
> One thing wasn't too clear is a resource basically number of CPUs and GPUs?

For details like this see the api docs: https://pytorch.org/torchx/latest/specs.html#resource. 

=====
>  Would be helpful to add some helper enum which includes something higher level like a V100 machine for provisioning

We really can't manage per-CSP mappings, hence we defer this for the end user to configure (via named resource) if they really need something as specific as V100. We however do manage named resources for fb-internal machine types.

=====
> Example has no main function

component python files are not really meant to be executed as a script hence do not have main functions. You can read more about components in torchx here: https://pytorch.org/torchx/latest/basics.html#components

=====
> I'm not sure what the entire Application Examples notebooks do? May be best to refactor together with pipeline examples? Let me know I can send a PR to delete

see my comment above. app and pipeline examples serve two different purposes. pipelines are not the only feature in torchx.

=====
> Make it clearer that pipeline.yaml is generated and not an input - I kept looking for it in the source directory

I believe the example clearly states this:
![image](https://user-images.githubusercontent.com/43595115/134957729-9fc3fd52-2f3a-4c6c-ba24-335e4e02f5f9.png)

=====
> Why is torch.elastic mentioned here? Whole repo feels like it needs a glossary. For example by image do you mean docker image?

The documentation says it "A Role for which the user provided entrypoint is executed with the torchelastic agent (in the container). Note that the torchelastic agent invokes multiple copies of entrypoint." - elastic is mentioned here because that role will wrap your given entrypoint with the torchelastic agent.

RE: about image - see https://pytorch.org/torchx/latest/specs.html#role. (there is a "note" box explaining what an image is)
![image](https://user-images.githubusercontent.com/43595115/134957333-afa5a605-ec5e-4ca3-ad59-67141fb45020.png)

=====
> Just sat TBD - delete for now?

we're still in beta, expect placeholders like these until we go to stable.

=====
> Have a link to supported utils in the codebase

Each utils component has a link to SOURCE on the RHS
![image](https://user-images.githubusercontent.com/43595115/134957288-ec72cb04-e680-40dc-b613-b65f67699820.png)

=====
> This says coming soon but looks like feature is available?

We've not released the head of "main" yet. See: https://pytorch.org/torchx/main/schedulers/kubernetes.html

=====
> Also empty just remove

Thanks for the suggestion. We'll continue having placeholders like this until we are fully in stable.

**Comment by kiukchung** [comment]
feel free to reopen
