### ISSUE TITLE
Support EFA for AWS Batch Scheduler

### ISSUE THREAD

**Issue by yukunlin** [pytorch/torchx#438]
## Description
Allow setting of job definition fields that enable Elastic Fabric Adapter (EFA) on supported instances.

## Motivation/Background
Elastic Fabric Adapter (EFA) is a network device that allows for faster network communication between instances. This is important for reducing the networking overhead that can slow down multi-node jobs.

## Detailed Proposal
On supported instances types (i.e. `p3dn.24xlarge`) that have the EFA drivers installed, EFA can be enabled for the batch jobs running with docker by passing through the EFA device. This is done by setting `LinuxParameters` in the job definition [[1]](https://docs.aws.amazon.com/batch/latest/userguide/efa.html):

```json
"linuxParameters": {
    "devices": [
      {
        "hostPath": "/dev/infiniband/uverbs0"
      }
    ]
}
```

To enable setting these parameters, we can hook into where `LinuxParameters` is already being set: https://github.com/pytorch/torchx/blob/1e2cb225036d9d7a5ee46732bc8f955eb147b5f6/torchx/schedulers/aws_batch_scheduler.py#L144-L148

We control whether or not the above configuration is set via a parameter for the batch scheduler 

## Alternatives
I'm not sure if there's a way to make setting the EFA configuration automatic in a non-fragile way. TorchX doesn't have control of what underlying EC2 instances are in use, and whether or not those are set up with EFA. 

In theory, TorchX could introspect the resources via the AWS APIs to check if the instances used by the batch queue has an EFA enabled network interface, but it still won't be able to confirm if those instances have the drivers installed. There could be some undesirable side effect of passing through the EFA device when the underlying host doesn't have the drivers.

Therefore, using a parameter to control setting the EFA configuration seems to be the simplest way to do things.

## Additional context/links
* https://docs.aws.amazon.com/batch/latest/userguide/efa.html
* https://aws.amazon.com/blogs/compute/leveraging-efa-to-run-hpc-and-ml-workloads-on-aws-batch/

**Comment by d4l3k** [comment]
Do we need to use the linuxParameters.devices or can we just use the existing bindmount support to bind in the entire `/dev/infiniband/` directory?

**Comment by d4l3k** [comment]
@yukunlin does

```
$ torchx run -s aws_batch dist.ddp --mount type=bind,src=/dev/infiniband,dst=/dev/infiniband ...
```
work for you?

**Comment by d4l3k** [comment]
One data point is that Kubernetes doesn't expose `--devices` for docker. https://stackoverflow.com/questions/59290752/how-to-use-device-dev-video0-with-kubernetes

The work around seems to be setting privileged mode and bind mounting them in. Would be nice to be able to support EFA via EKS as well

**Comment by d4l3k** [comment]
just verified, bindmounting without --privileged doesn't work due to the devices cgroup controller

**Comment by yukunlin** [comment]
> I believe we can make this part of the resource specs (just like we do for sharedMemorySize = role.resource.memMB) we can take this from the [resource.capabilities](https://github.com/pytorch/torchx/blob/main/torchx/specs/api.py#L64) map

@kiukchung I prefer the PR that @d4l3k put out to add the device mount via argument. Instances that support EFA aren't guaranteed to be launched with them, or have the drivers installed. Hence, best to leave it to the user to decide whether or not to mount, as mounting to non existent devices could have other side effects.

**Comment by kiukchung** [comment]
yes after investigation we don’t have a choice but to do it as a runopt because unfortunately not all schedulers that support docker as the container exposes /dev using the same methodology. For instance k8s requires you use the k8s device plugin (which is how it works on eks) whereas batch requires you to pass linuxParameters in the job def.

**Comment by d4l3k** [comment]
Mounting it when it's not present fails the batch job. And yeah this is super config specific, getting a EFA enabled batch environment was such a pain. Custom launch templates + a EFA enabled docker container is really fragile/tricky to setup. It would be great to have something more automatic but that requires a lot of work from AWS side

I am tempted to add mounts to the resources side as well since that might be useful to share that across users but like @yukunlin mentioned that also requires the queue and image being configured appropriately so might be best to have the user aware of it

Interestingly Kubernetes handles this much more gracefully with device plugins so maybe ECS should always automount EFA devices if they're available (or have a flag to automount)

**Comment by kiukchung** [comment]
> Instances that support EFA aren't guaranteed to be launched with them, or have the drivers installed. 

this is less of a concern since you SHOULD be installing the drivers and enabling efa on instances that support them. Otherwise it’s a moot point to use those instances. Better switch to a p3 if you’re not going to use efa in p3d and the same goes for c5 vs c5d.
