### ISSUE TITLE
Support headers and request verification options for Ray Client

### ISSUE THREAD

**Issue by KPostOffice** [pytorch/torchx#752]
## Description
The Ray SDK has options for specifying headers as well as a flag for HTTPS verification that are not exposed in anyway within torchx when submitting jobs.

## Motivation/Background
We are looking to put our Ray instance behind an OAuth server. This means that communicating with it will require setting an authorization header as well as specifying the self signed cert that we create for it.

## Detailed Proposal
Expose these options to torchx users.

## Alternatives
We will create a custom fork of torchx which provides these options.

## Additional context/links
https://github.com/ray-project/ray/blob/5435807cb429b89bc7bb3f61464131d41f60460f/dashboard/modules/dashboard_sdk.py#L206-207

**Comment by kiukchung** [comment]
As @d4l3k mentioned on the torchx slack channel, there's a couple of approaches (with varying degrees of difficulty vs clean-ness trade-off). I'll start with the easiest (albeit hackiest):

1. **Leverage environment variables**. If the Ray client reads http headers from env vars, then you can create a custom component and hard-code the default auth headers for your organization. This requires no code change in torchx. If the Ray client doesn't support  setting http headers via env vars, then you would have to edit [`torchx.schedulers.RayScheduler`](https://github.com/pytorch/torchx/blob/main/torchx/schedulers/ray_scheduler.py#L115) to read the headers off of env vars and pass them when creating the Ray client.
2. **Add optional constructor args to `RayScheduler`**. Similar to `client` and `docker_client` optional args to the [`KubernetesScheduler`](https://github.com/pytorch/torchx/blob/main/torchx/schedulers/kubernetes_scheduler.py#L540-L541). If you are using torchx programmatically then you'd create the `RayScheduler` with the newly added extra args. To make this work from the torchx CLI as well you'd have to plumb it through the [`get_runner()`](https://github.com/pytorch/torchx/blob/3a253be910cd1029bb00bb4ed97a5c68cbd4ff10/torchx/runner/api.py#L682) method and the call-sites of `get_runner()` in the `cmd_<API>.py` (see [link](https://github.com/search?q=repo%3Apytorch%2Ftorchx+get_runner%28+path%3A%2F%5Etorchx%5C%2Fcli%5C%2F%2F&type=code)) files.
3. **Modify other runner and scheduler APIs to take a run `cfg`**. The [`run`](https://github.com/pytorch/torchx/blob/main/torchx/runner/api.py#L219)` API already takes a `cfg`, which is read from `.torchxconfig` file. This is the most involved (but not difficult) to do since it is aan API (but not functional) BC breaking change and requires the author to modify the `list`, `cancel`, `status`, `log`, and `describe` APIs for both the runner and scheduler interfaces and plumb the `cfg` object in all the call-sites. One would also have to change all the scheduler implementations to conform to the new API. One would also need the help of the torchx team at Meta since this requires the Meta-internal scheduler implementations to also adopt the new API.

From our discussions on slack, it seems like (2) is the way to go since you're using torchx programmatically and we already have precedence in adding optional arguments to other schedulers like KubernetesScheduler in torchx.
